#!/usr/bin/python
# -*- coding: utf-8 -*-

import requests
import json
import sys
import dotenv


def decodeJson(jfile):
    return json.loads(jfile)


def sendRequest(busStop):
    dotenv.load()
    try:
        if (dotenv.get('APP_ID') or dotenv.get('API_KEY')):
            raise NameError('MissingAPIandAPPID')
        r = requests.post(
            'https://api.octranspo1.com/v1.2/GetNextTripsForStopAllRoutes',
            data={
                "appID": dotenv.get('APP_ID'),
                "apiKey": dotenv.get('API_KEY'),
                "stopNo": busStop,
                "format": "json"
            }
        ).json()
        return r
    except requests.exceptions.ConnectionError:
        print "There is no Internet connection :("
        exit()


def busSchedule(data):
    print data['GetRouteSummaryForStopResult']['StopNo'] + " - " + str(
        data['GetRouteSummaryForStopResult']['StopDescription']
    )
    if 'Trips' in data['GetRouteSummaryForStopResult']['Routes']['Route']:
        print "\033[1;4;32mRoute " + str(
            data['GetRouteSummaryForStopResult']['Routes']['Route']['RouteNo']
        ) + "\033[0m"
        route = data['GetRouteSummaryForStopResult']['Routes']['Route']
        trips = route['Trips']['Trip']
        for trip in trips:
            print "\033[32mTrip Destination: \033[0m" + trip['TripDestination']
            print "\033[32mAdjusted Schedule Time: \033[0m " + str(
                trip['AdjustedScheduleTime']
            ) + " minutes"
    else:
        for bus in data['GetRouteSummaryForStopResult']['Routes']['Route']:
            if 'Trips' in bus and len(bus['Trips']) > 0:
                print "\033[1;4;32mRoute " + str(bus['RouteNo']) + "\033[0m"
                for trip in range(len(bus['Trips'])):
                    try:
                        print "\033[32mTrip Destination: \033[0m" + str(
                            bus['Trips'][trip]['TripDestination']
                        )
                        print "\033[32mAdjusted Schedule Time: \033[0m " + str(
                            bus['Trips'][trip]['AdjustedScheduleTime']
                        ) + " minutes"
                    except:
                        # print bus['Trips'][trip]['AdjustedScheduleTime']
                        print "\033[32mTrip Destination: \033[0m" + str(
                            bus['Trips'][trip]['TripDestination'].encode(
                                'ascii', 'ignore'
                            )
                        )
                        print "\033[32mAdjusted Schedule Time: \033[0m " + str(
                            bus['Trips'][trip]['AdjustedScheduleTime'].encode(
                                'ascii', 'ignore'
                            )
                        ) + " minutes"


def main():
    jdata = ""
    try:
        jdata = sendRequest(sys.argv[1])
        busSchedule(jdata)
    except IndexError:
        try:
            busStop = raw_input("ENTER THE STOP NUMBER >>> ")
            while len(busStop) != 4 or not busStop.isdigit():
                busStop = raw_input("ENTER THE STOP NUMBER >>> ")
            jdata = sendRequest(busStop)
            busSchedule(jdata)
        except KeyboardInterrupt:
            print "\nBye Bye!"
            exit()


if __name__ == "__main__":
    main()
