#!/usr/bin/python
# -*- coding: utf-8 -*-

import requests
import json
import sys
import dotenv

# Constants
ESC_CHAR = '\033'
COLOR_GREEN = '32m'
RESET = '[0m'


def decodeJson(jfile):
    return json.loads(jfile)


def sendRequest(busStop):
    dotenv.load()
    try:
        if (not(dotenv.get('APP_ID') or dotenv.get('API_KEY'))):
            raise NameError('MissingAPIandAPPID')
        r = requests.post(
            'https://api.octranspo1.com/v1.2/GetNextTripsForStopAllRoutes',
            data={
                "appID": dotenv.get('APP_ID'),
                "apiKey": dotenv.get('API_KEY'),
                "stopNo": busStop,
                "format": "json"
            }
        ).json()
        return r
    except requests.exceptions.ConnectionError:
        print "There is no Internet connection :("
        exit()


def busSchedule(data, busNumbers):
    print "{} - {}".format(
        data['GetRouteSummaryForStopResult']['StopNo'],
        data['GetRouteSummaryForStopResult']['StopDescription']
    )
    if 'Trips' in data['GetRouteSummaryForStopResult']['Routes']['Route']:
        print "{0}[1;4;{2}Route {1}{0}{3}".format(
            ESC_CHAR,
            data['GetRouteSummaryForStopResult']['Routes']['Route']['RouteNo'],
            COLOR_GREEN,
            RESET
        )
        route = data['GetRouteSummaryForStopResult']['Routes']['Route']
        trips = route['Trips']['Trip']
        for trip in trips:
            print "{0}[{2}Trip Destination: {0}{3}{1}".format(
                ESC_CHAR,
                trip['TripDestination'],
                COLOR_GREEN,
                RESET
            )
            print "{0}[{2}Adjusted Schedule Time: {0}{3} {1} minutes".format(
                ESC_CHAR,
                trip['AdjustedScheduleTime'],
                COLOR_GREEN,
                RESET
            )
    else:
        for bus in data['GetRouteSummaryForStopResult']['Routes']['Route']:
            if 'Trips' in bus and len(bus['Trips']) > 0:
                print "{0}[1;4;{2}Route {1}{0}{3}".format(
                    ESC_CHAR,
                    str(bus['RouteNo']),
                    COLOR_GREEN,
                    RESET
                )
                for trip in range(len(bus['Trips'])):
                    # try:
                    print "{0}[{2}Trip Destination: {0}{3}{1}".format(
                        ESC_CHAR,
                        bus['Trips'][trip]['TripDestination'].encode('utf-8'),
                        COLOR_GREEN,
                        RESET
                    )
                    print str(
                        "{0}[{2}Adjusted Schedule Time: {0}{3} {1} minutes"
                    ).format(
                        ESC_CHAR,
                        bus['Trips'][trip]['AdjustedScheduleTime'],
                        COLOR_GREEN,
                        RESET
                    )


def main():
    jdata = ""
    busNumber = []
    if len(sys.argv) > 2:
        busNumber = sys.argv[2:len(sys.argv)]
    try:
        jdata = sendRequest(sys.argv[1])
        busSchedule(jdata, busNumber)
    except IndexError:
        try:
            busStop = raw_input("ENTER THE STOP NUMBER >>> ")
            while len(busStop) != 4 or not busStop.isdigit():
                busStop = raw_input("ENTER THE STOP NUMBER >>> ")
            jdata = sendRequest(busStop)
            busSchedule(jdata, busNumber)
        except KeyboardInterrupt:
            print "\nBye Bye!"
            exit()


if __name__ == "__main__":
    main()
